#!/usr/bin/env python3

from base64 import b64decode

def xor(a, b):
    return bytes([x^y for x,y in zip(a,b)])

m = '104e137f425954137f74107f525511457f5468134d7f146c4c'

for x in range(0xFF):
    key_str = ''
    for y in range(26):
        key_str += hex(x)[2:]
    a = xor(bytes.fromhex(m), bytes.fromhex(key_str))
    print(a)




